### PR TITLE
Add codecov GitHub action

### PR DESCRIPTION
**Pull request by jawsvk**
## Related Issues & Documents (if needed)
Issue #13 
## What type of PR is this? (check all applicable)

- [ ] Refactoring existing code
- [ ] Adding tests to existing code
- [x] New Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## QA Instructions(if necessary), Screenshots of Output or Recordings

Should see GitHub Actions running against Pull Requests

## Added tests?

- [ ] Yes
- [x] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation / readme or updated requirements.txt(if needed)?

- [ ] Changed documentation in readme
- [x] No documentation needed
- [ ] Updated requirements.txt

### CODE REVIEW

**Comment by jawsvk** [comment]
Finally it runs properly :)

**Comment by BALaka-18** [comment]
@jawsvk Great work ! I think there was some error with the corpus download part and the dependencies, right ? I couldn't figure out the solution for the nltk.download() part myself.
One last thing, just squash all commits to one single commit. I'll merge it then.

**Comment by jawsvk** [comment]
> @jawsvk Great work ! I think there was some error with the corpus download part and the dependencies, right ? I couldn't figure that out the solution for the nltk.download() part myself.
> One last thing, just squash all commits to one single commit. I'll merge it then.

Done!

**Review by BALaka-18 — APPROVED** [review]
Looks good. Merging.

**Pull request merged**
