### PR TITLE
CODE OF COCNDUCT FILE 

### PR DESCRIPTION
**Pull request by akrish4**
## What type of PR is this? (check all applicable)

- [x] Refactoring existing code
- [ ] Adding tests to existing code
- [x] New Feature
- [x] Bug Fix
- [x] Optimization
- [x] Documentation Update

## Screenshots 
coc1
coc2

No test  need for this pr since it is a documentation 

## Added tests?

- [ ] Yes
- [x] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation / readme or updated requirements.txt(if needed)?

- [x] Changed documentation in readme
- [x] No documentation needed (this itself is a documentation and links to this is already updated in readme and contributing)
- [ ] Updated requirements.txt

### CODE REVIEW

**Comment by akrish4** [comment]
@BALaka-18  Kindly do check and merge it and also pls do add the same labels added in the issue to pr also

**Comment by BALaka-18** [comment]
1. @akrish4 Please read the **[CONTRIBUTING.md](https://github.com/BALaka-18/rake_new2/blob/master/CONTRIBUTING.md)** carefully before sending a PR.
It clearly mentions that **all PRs must be sent to the DWOC-contributions branch and NOT the master branch.**
Send a PR to the correct branch.

2. Send in **ONLY** the Code of conduct file, no need to make changes to the README, and the CONTRIBUTING.md files. The maintainer will do them after the PR is merged.

Please follow these two points and I'll merge your new PR. Thanks.

**Comment by akrish4** [comment]
> 1. @akrish4 Please read the **[CONTRIBUTING.md](https://github.com/BALaka-18/rake_new2/blob/master/CONTRIBUTING.md)** carefully before sending a PR.
>    It clearly mentions that **all PRs must be sent to the DWOC-contributions branch and NOT the master branch.**
>    Send a PR to the correct branch.
> 2. Send in **ONLY** the Code of conduct file, no need to make changes to the README, and the CONTRIBUTING.md files. The maintainer will do them after the PR is merged.
> 
> Please follow these two points and I'll merge your new PR. Thanks.

Okay thank you @BALaka-18 
I will do it

**Comment by akrish4** [comment]
@BALaka-18  I have to close this pr right ?
so that i can open a new pr to the dwoc-contribution branch

**Comment by BALaka-18** [comment]
> @BALaka-18 I have to close this pr right?
> so that I can open a new pr to the dwoc-contribution branch

I'm closing it for you, send in a new one.

**Pull request closed without merging**
