### PR TITLE
[WIP] Literature survey

### PR DESCRIPTION
**Pull request by theodumont**
## Description of the change
[WIP] Add literature survey, as mentionned in #27 

## Related Issues & Documents (if needed)
#27 

## What type of PR is this? (check all applicable)

- [ ] Refactoring existing code
- [ ] Adding tests to existing code
- [ ] New Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## QA Instructions(if necessary), Screenshots of Output or Recordings
- [x] ok

## Added tests?
- [ ] Yes
- [x] No, because they aren't needed
- [ ] No, because I need help

## Added to documentation / readme or updated requirements.txt(if needed)?

- [ ] Changed documentation in readme
- [ ] No documentation needed
- [ ] Updated requirements.txt

### CODE REVIEW

**Comment by BALaka-18** [comment]
@theodumont are you still working on this ? Coz it shows WIP and the file isn't complete too.
If you do not wish to proceed any further I'll unassign you.

**Comment by theodumont** [comment]
@BALaka-18 I plan to finish the work. Sorry for the delay, the covid situation in my country forced me to put this off for a bit, you'll have some updates soon.

**Comment by theodumont** [comment]
I finished to write what I wanted to (the most famous keyword extraction methods). If you want me to detail some other methods I didn't talk about, feel free to ask me.

By the way, the LaTeX is broken sometimes, I'll try to fix this soon 😃

**Comment by BALaka-18** [comment]
Sure no problem. I understand.

**Pull request closed without merging**
